services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/home/server
    environment:
      - ${HOME_STORAGE}:/home/data
