services:
  backend-dev:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/home/server
      - ${HOME_STORAGE}:/home/data

  frontend-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./client:/home/client
