services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/home/server
      - ${HOME_STORAGE}:/home/data

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    ports:
      - "8001:80"
    